# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solve equation 2 of the EM algorithm
#'
#' @param y, a vector of forecasts
#' @param ftk, a vector of the forecasts
#' @export
est_zhat <- function(y, ftk) {
    .Call('_EMalg_est_zhat', PACKAGE = 'EMalg', y, ftk)
}

